### ISSUE TITLE
Keep getting the same error when enabling JIT

### ISSUE THREAD

**Issue by letsgoyippeeee** [plizeee/AutoJIT#1]
AutoJIT
290
processName: DolphiniOS
deviceName: iPhone
/Users/user/Downloads/AutoJIT/ main.applescript:7459:7552: execution error: /Users/user/Downloads/AutoJIT/ scripts/isWaiting.applescript:1228:1232: execution error: Can't make «class valL»
of item 1 of {} into type text. (-1700) (1)

Any help? Thanks for making this shortcut as it is really helpful, just trying to figure out what’s wrong.

**Comment by plizeee** [comment]
At the top of the left sidebar in Xcode, make sure the little spray paint tab is the one selected. It's not selected by default, so I'll update the instructions and will try and automate that when I get a chance. 

Let me know if that solves your issue!

**Comment by letsgoyippeeee** [comment]
That worked! Thanks so much

**Comment by letsgoyippeeee** [comment]
That worked! Thanks so much
